--local dap = require('dap')
--dap.adapters.cppdbg = {
--    id = 'cppdbg',
-- 	type = 'executable',
--    command = '/home/evajust/.vscode/extensions/ms-vscode.cpptools-1.20.5-linux-x64/debugAdapters/bin/OpenDebugAD7'
--}
--
